import os
import asyncio
import pandas as pd
import edge_tts

# 1. Path Configurations
CSV_FILE = "/home/miku/Code/AnkiGenerater/ankigen/word/chinese_extend.csv"

# Separate folders for vocabulary words and full sentences
VOCAB_OUTPUT_FOLDER = "/home/miku/Code/AnkiGenerater/ankigen/voice/chinese"
SENTENCE_OUTPUT_FOLDER = "/home/miku/Code/AnkiGenerater/ankigen/voice/chinese_sentences"

# Column names in your CSV matching your previous pipeline outputs
VOCAB_COLUMN = "Vocab"
EXAMPLE_COLUMN = "Example"  # The Chinese example sentence column generated by Qwen

# Select a Mandarin Chinese voice
VOICE = 'zh-CN-XiaoxiaoNeural' 

# Create target directories if they don't exist
os.makedirs(VOCAB_OUTPUT_FOLDER, exist_ok=True)
os.makedirs(SENTENCE_OUTPUT_FOLDER, exist_ok=True)

async def download_audio(text, target_folder, filename):
    """Asynchronous function to download audio from Edge TTS into a specific target folder"""
    path = os.path.join(target_folder, filename)
    
    if os.path.exists(path):
        return  # Skip if the file already exists
        
    try:
        communicate = edge_tts.Communicate(text, VOICE)
        await communicate.save(path)
        print(f"✓ Downloaded: {filename} -> {os.path.basename(target_folder)}")
    except Exception as e:
        print(f"✗ Error downloading audio for '{text}': {e}")

async def main():
    try:
        df = pd.read_csv(CSV_FILE)
    except FileNotFoundError:
        print(f"File not found: {CSV_FILE}. Please double-check the path!")
        return

    print(f"Found {len(df)} rows in the CSV file. Starting audio batch engine...")

    for index, row in df.iterrows():
        vocab = str(row.get(VOCAB_COLUMN, "")).strip()
        sentence = str(row.get(EXAMPLE_COLUMN, "")).strip()
        
        # --- Task 1: Generate Vocabulary Audio ---
        if vocab and vocab != 'nan':
            vocab_filename = f"{vocab}.mp3"
            await download_audio(vocab, VOCAB_OUTPUT_FOLDER, vocab_filename)
            
        # --- Task 2: Generate Example Sentence Audio ---
        if sentence and sentence != 'nan':
            # Name the sentence audio file uniquely so it matches your vocab mapping
            sentence_filename = f"{vocab}_sentence.mp3"
            await download_audio(sentence, SENTENCE_OUTPUT_FOLDER, sentence_filename)
        
        # Tiny dynamic delay to honor server limits gently
        await asyncio.sleep(0.15)

    print("\n🎉 Completed! Audio resources generated successfully:")
    print(f"   - Words folder: {VOCAB_OUTPUT_FOLDER}")
    print(f"   - Sentences folder: {SENTENCE_OUTPUT_FOLDER}")

if __name__ == "__main__":
    asyncio.run(main())