[project]
name = "anki-generate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas",
    "edge-tts",
    "tqdm",
    "requests",
    "deep-translator",
    "ollama",
    "pydantic",
    "diffusers",
    "torch",
    "transformers",
    "accelerate",
    "genanki",
    "argostranslate",
    "pypinyin",
    "beautifulsoup4",
]
